### ISSUE TITLE
workflow: add interpretations from /unattached

### ISSUE THREAD

**Issue by kohath** [Rexko/rexko#106]
The only purpose of /unattached is to bring up a list of unattached items and attach them.  Currently this can only be done by clicking through to each individual item; it'd be easier just to be able to add parses from scratch in situ.

**Comment by Muskworker** [comment]
/unattached isn't an edit page and we shouldn't be trying to make it one.   (It might ought to go away altogether, like /matching per #190.)

This is a detail edit, and it's too detailed for the main lexeme form.  Stick with it being on the locus page until we get a more convenient way to edit more detailed parts of the lexeme.

wontfix for now.
